import { PUBLIC_APP_URL } from "$env/static/public";

export type DNSHeader = {
	id: "spf" | "domain-lockdown" | "dkim" | "dmarc";
	type: "TXT";
	name: string;
	value: string;
	ttl: string;
	required: "Required" | "Optional";
};

export const HEADERS: DNSHeader[] = [
	{
		id: "spf",
		type: "TXT",
		name: "@",
		value: "v=spf1 a mx include:relay.mailchannels.net ~all",
		ttl: "Auto",
		required: "Required"
	},
	{
		id: "domain-lockdown",
		type: "TXT",
		name: "_mailchannels",
		value: "v=mc1 cfid=" + PUBLIC_APP_URL,
		ttl: "Auto",
		required: "Required"
	},
	{
		id: "dkim",
		type: "TXT",
		name: "mailflare._domainkey",
		value: "v=DKIM1; p=[public key generated by following the instructions given below]",
		ttl: "Auto",
		required: "Optional"
	},
	{
		id: "dmarc",
		type: "TXT",
		name: "_dmarc",
		ttl: "Auto",
		value: "v=DMARC1; p=none",
		required: "Optional"
	}
];
